services:
  postgres:
    container_name: pg_sql2
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pacientes
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped