jwt:
  access:
    key:
      public: classpath:app.pub
      private: classpath:app.key
  refresh:
    key:
      public: classpath:app_refresh.pub
      private: classpath:app_refresh.key

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pacientes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      datasource-platform: org.hibernate.dialect.PostgreSQLDialect
